// @generated by deriveStatePropertyTests, then adapted for compilation.
// Source: deriveStatePropertyTests(loadStateMachineDefinition(reservation.yaml)).
// The generator's raw output referenced an undefined module-level `m` and
// lower-cased state names; this adapted copy fixes those seams so the four
// yaml invariants are actually exercised. Regeneration re-runs the generator;
// re-apply the adapter fixes (see git history of this file).
// Lives in test/ (not src/domain/) so the project vitest config collects it.

import fc from "fast-check";
import { ReservationMachine } from "../src/domain/reservations/reservation-machine.js";

describe("Reservation State Machine — derived properties (REQ-09)", () => {
  it("终态（CheckedOut/NoShow/Cancelled）不得有出边", () => {
    fc.assert(
      fc.property(fc.constantFrom<string>("CheckedOut", "NoShow", "Cancelled"), (state) => {
        const m = new ReservationMachine(state);
        expect(() => m.transition("Any")).toThrow(/terminal|no.*transition/i);
      }),
    );
  });

  it("Cancelled 只能从 Booked 或 Confirmed 达到，入住后不可取消", () => {
    fc.assert(
      fc.property(fc.constantFrom(...ReservationMachine.nonTerminalStates), (fromState) => {
        // Cancelled is reachable only from Booked or Confirmed, never from CheckedIn.
        const canReach = new ReservationMachine(fromState).canTransitionTo("Cancelled", fromState);
        if (fromState === "Booked" || fromState === "Confirmed") {
          expect(canReach).toBe(true);
        } else {
          expect(canReach).toBe(false);
        }
      }),
    );
  });

  it("NoShow 需满足到店截止条件，不能在入住日前标记", () => {
    fc.assert(
      fc.property(fc.constantFrom(...ReservationMachine.nonTerminalStates), (fromState) => {
        const m = new ReservationMachine(fromState);
        // NoShow transitions require the arrival_cutoff guard.
        const reachRequiresCutoff = m.canTransitionTo("NoShow", fromState)
          ? m.hasCondition("arrival_cutoff")
          : true;
        expect(reachRequiresCutoff).toBe(true);
      }),
    );
  });

  it("CheckedOut 需要 Folio 已结算，不允许未结账退房", () => {
    fc.assert(
      fc.property(fc.constantFrom(...ReservationMachine.nonTerminalStates), (fromState) => {
        const m = new ReservationMachine(fromState);
        const reachRequiresFolio = m.canTransitionTo("CheckedOut", fromState)
          ? m.hasCondition("folio_settled")
          : true;
        expect(reachRequiresFolio).toBe(true);
      }),
    );
  });
});
