// Assembly fingerprint — extract a content-agnostic structural fingerprint
// from the forge-dispatcher pipeline output.
//
// The fingerprint captures WHICH structural decisions the assembly pipeline
// made (subcommand, dispatchMode, resolved lib path, allowed tools, whether
// the untrusted-fence preamble survived, hint tags) — NOT the markdown body.
// This separates "contract broken" (fence dropped, hints became override,
// tools missing) from "wording changed" (a lib-doc sentence rewritten), so
// a snapshot over the fingerprint catches catastrophic regressions without
// noise from routine doc edits.
//
// Validates: Requirement R1 (prompt-assembly-snapshot)

import { UNTRUSTED_PREAMBLE } from "./untrusted-fence.js";

/**
 * Structural fingerprint of an assembled dispatch result.
 *
 * Every field is content-agnostic and JSON-serialisable so it can be stored
 * as a golden fixture and compared with deep equality.
 */
export interface AssemblyFingerprint {
  /** The resolved subcommand name (e.g. "build"). */
  subcommand: string;
  /** The dispatch_mode parsed from lib frontmatter (e.g. "inline" | "fork"). */
  dispatchMode: string;
  /** Resolved lib instruction path, relative to plugin root. */
  resolvedLibPath: string;
  /** Allowed tools declared in frontmatter, sorted + de-duplicated. */
  allowedTools: string[];
  /** Whether the UNTRUSTED_PREAMBLE fence contract is intact in the context. */
  hasUntrustedPreamble: boolean;
  /** Hint tags generated by the router, sorted for stable comparison. */
  hintTags: string[];
}

/** Input to extractFingerprint — the structural signals from the pipeline. */
export interface FingerprintInput {
  subcommand: string;
  dispatchMode: string;
  resolvedLibPath: string;
  allowedTools: string[];
  /** The assembled context block (fence wrapper + injected content). */
  contextBlock: string;
  hintTags: string[];
}

/**
 * Sentinel error thrown when a required structural field is missing.
 *
 * Naming the field makes a half-assembled pipeline result immediately
 * diagnosable instead of producing a silently-malformed fingerprint.
 */
export class FingerprintMissingField extends Error {
  constructor(field: string) {
    super(`FingerprintMissingField: '${field}' is empty — pipeline result incomplete`);
    this.name = "FingerprintMissingField";
  }
}

/**
 * Extract a deterministic, content-agnostic structural fingerprint.
 *
 * - `allowedTools` and `hintTags` are sorted + de-duplicated so input order
 *   never causes spurious snapshot drift.
 * - `hasUntrustedPreamble` requires the *exact* preamble string, not a
 *   substring heuristic — a tampered/partial preamble counts as missing,
 *   which is precisely the regression this layer exists to catch.
 *
 * @throws {FingerprintMissingField} when dispatchMode or resolvedLibPath is empty.
 */
export function extractFingerprint(input: FingerprintInput): AssemblyFingerprint {
  if (!input.dispatchMode) {
    throw new FingerprintMissingField("dispatchMode");
  }
  if (!input.resolvedLibPath) {
    throw new FingerprintMissingField("resolvedLibPath");
  }

  return {
    subcommand: input.subcommand,
    dispatchMode: input.dispatchMode,
    resolvedLibPath: input.resolvedLibPath,
    allowedTools: dedupSorted(input.allowedTools),
    hasUntrustedPreamble: input.contextBlock.includes(UNTRUSTED_PREAMBLE),
    hintTags: dedupSorted(input.hintTags),
  };
}

/** De-duplicate and sort a string array for stable fingerprint comparison. */
function dedupSorted(items: string[]): string[] {
  return Array.from(new Set(items)).sort();
}
