/**
 * Knowledge Catalog — Layer A progressive index (~50 lines) for
 * `.forge/knowledge/`.
 *
 * Motivation
 * ----------
 * The `/tinkerman learn` skill maintains `instincts.md`, `solutions/*.md`,
 * `known-failures.md` and `evolved-rules.md`. Before a new `/tinkerman plan`
 * researches the knowledge base, it has to either read every file in full
 * or guess which one is relevant. That does not scale well as the knowledge
 * base grows towards `knowledge_limit` (default 20) entries.
 *
 * This module generates a single ~50-line `catalog.md` summary of what the
 * knowledge base currently holds. The intent is not to replace the detailed
 * files; it is to give the plan/build/debug phases a cheap entry point that
 * tells them "what exists" before they decide "what to read in full".
 *
 * Design notes
 * ------------
 * - Pure functions. All parsers take strings; `buildCatalog` composes them
 *   and renders markdown. A thin driver reads/writes the files.
 * - Input parsing is defensive: malformed sections degrade to zero counts
 *   rather than throwing. The catalog is a derived view, never the source
 *   of truth, so it should never block learn.
 * - Output is deterministic given the same inputs: categories are sorted,
 *   numbers are rendered without locale-sensitive separators, and the
 *   trailing newline is fixed.
 *
 * **Generated by**: `/tinkerman learn` epilogue (open zone, regenerated every
 * run — like `evolution-report.md`, not retained as history).
 */

import type { Pattern } from "./pattern-stats.js";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * Per-file summary of a `solutions/<topic>.md` knowledge document.
 *
 * `confidence` is the frontmatter value; empty tags are dropped upstream.
 * `ageDays` is optional so callers that only have the date string can still
 * produce a catalog without computing it themselves.
 *
 * @internal
 */
export interface SolutionSummary {
  topic: string;
  title: string;
  confidence: number;
  tags: string[];
  date: string;
  ageDays?: number;
}

/**
 * Aggregate counters for `known-failures.md`.
 *
 * We do not surface individual failure entries in the catalog; a count plus
 * the most recent occurrence is enough for the Research step to decide
 * whether to open the file.
 *
 * @internal
 */
export interface FailureSummary {
  patternCount: number;
  lastUpdated: string;
}

/**
 * Aggregate counters for `evolved-rules.md`.
 *
 * Active + retired totals let the catalog surface rule capacity at a
 * glance. `staleCandidates` is the number of active rules whose
 * `Last_triggered` is older than the staleness threshold — the learn skill
 * already computes this, so the catalog only needs the integer.
 *
 * @internal
 */
export interface EvolvedRulesSummary {
  activeCount: number;
  retiredCount: number;
  staleCandidates: number;
}

/**
 * Inputs to {@link buildCatalog}. Every field is optional so the catalog
 * degrades gracefully on empty knowledge bases.
 *
 * @internal
 */
export interface CatalogInput {
  patterns?: Pattern[];
  solutions?: SolutionSummary[];
  failures?: FailureSummary;
  rules?: EvolvedRulesSummary;
  generatedAt: Date;
  limit?: number;
}

// ---------------------------------------------------------------------------
// Parsing
// ---------------------------------------------------------------------------

/**
 * Extract the YAML frontmatter fields the catalog cares about from a single
 * `solutions/<topic>.md` document.
 *
 * Returns `null` when the document lacks a recognizable frontmatter block so
 * the caller can skip it. `topic` is the kebab-case filename without the
 * `.md` extension, supplied by the driver.
 *
 * @internal
 */
export function parseSolutionFrontmatter(topic: string, content: string): SolutionSummary | null {
  const fmMatch = content.match(/^---\n([\s\S]*?)\n---\n/);
  if (!fmMatch) return null;
  const block = fmMatch[1];

  const title = readYamlString(block, "title") ?? topic;
  const date = readYamlString(block, "date") ?? "";
  const confidence = Number(readYamlString(block, "confidence") ?? "0");
  const tags = readYamlArray(block, "tags");

  return {
    topic,
    title,
    confidence: Number.isFinite(confidence) ? confidence : 0,
    tags,
    date,
  };
}

/**
 * Count the failure patterns recorded in `known-failures.md` and return the
 * `updated` date from its frontmatter.
 *
 * A failure "pattern" is an H3 heading (`### ...`). Empty files or files
 * that only contain the HTML comment template produce a zero count.
 *
 * @internal
 */
export function parseFailureSummary(content: string): FailureSummary {
  const patternCount = (content.match(/^###\s+/gm) ?? []).length;
  const lastUpdated = readYamlString(extractFrontmatter(content), "updated") ?? "";
  return { patternCount, lastUpdated };
}

/**
 * Summarize `evolved-rules.md` by counting active rules, retired rules, and
 * identifying staleness candidates.
 *
 * The parser is scoped to two sections: everything above the `## Retired
 * Rules` heading is "active", everything below is "retired". Any H3 that
 * starts with `### R` is counted as a rule; other H3s (e.g. the Retired
 * Rules enumeration if it ever uses `###`) are ignored.
 *
 * `staleCandidates` matches the existing `evolved-rules-staleness` threshold
 * (>= 5 sessions elapsed); callers can override by passing a pre-computed
 * count.
 *
 * @internal
 */
export function parseEvolvedRulesSummary(
  content: string,
  precomputedStale?: number,
): EvolvedRulesSummary {
  const retiredHeadingRe = /^##\s+Retired Rules\s*$/im;
  const retiredIdx = content.search(retiredHeadingRe);
  const active = retiredIdx >= 0 ? content.slice(0, retiredIdx) : content;
  const retired = retiredIdx >= 0 ? content.slice(retiredIdx) : "";

  const activeCount = (active.match(/^###\s+R\d+:/gm) ?? []).length;
  // Retired rules in the current file use bullet form ("- **R-retired-N**:")
  // instead of H3s. Accept both shapes so we do not under-count.
  const retiredH3 = (retired.match(/^###\s+R/gm) ?? []).length;
  const retiredBullet = (retired.match(/^-\s+\*\*R-retired-/gm) ?? []).length;
  const retiredCount = retiredH3 + retiredBullet;

  return {
    activeCount,
    retiredCount,
    staleCandidates: precomputedStale ?? 0,
  };
}

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

/**
 * Render the catalog markdown.
 *
 * Layout (Layer A progressive index):
 *   1. H1 banner + generation timestamp.
 *   2. One-line totals row (patterns, solutions, failures, rules).
 *   3. Top-confidence solutions table (up to 5 rows).
 *   4. Instinct patterns grouped by tag (up to 6 rows).
 *   5. Pointers to full files for deep reads.
 *
 * Length target: ≤ 60 lines including blank lines. Longer inputs are
 * truncated with a trailing "… and N more" marker so the file stays
 * readable.
 *
 * @internal
 */
export function renderCatalog(input: CatalogInput): string {
  const { patterns = [], solutions = [], failures, rules, generatedAt, limit } = input;

  const lines: string[] = [];
  lines.push("---");
  lines.push(`generated: ${toIsoDate(generatedAt)}`);
  lines.push("auto_generated: true");
  lines.push("---");
  lines.push("");
  lines.push("# Knowledge Catalog");
  lines.push("");
  lines.push(
    "Layer A index. Regenerated by `/tinkerman learn`. Read this before opening " +
      "`instincts.md` or `solutions/*.md` — it tells you what exists without " +
      "paying the full-file cost.",
  );
  lines.push("");

  // Totals
  const limitClause = limit ? ` / ${String(limit)}` : "";
  lines.push("## Totals");
  lines.push("");
  lines.push("| Bucket | Count |");
  lines.push("|--------|-------|");
  lines.push(`| Instinct patterns (\`instincts.md\`) | ${String(patterns.length)} |`);
  lines.push(`| Solution docs (\`solutions/\`) | ${String(solutions.length)}${limitClause} |`);
  if (failures) {
    lines.push(`| Known failures (\`known-failures.md\`) | ${String(failures.patternCount)} |`);
  }
  if (rules) {
    lines.push(
      "| Evolved rules (active / retired) | " +
        String(rules.activeCount) +
        " / " +
        String(rules.retiredCount) +
        (rules.staleCandidates > 0
          ? ` · ⚠ ${String(rules.staleCandidates)} stale candidate(s)`
          : "") +
        " |",
    );
  }
  lines.push("");

  // Top solutions
  if (solutions.length > 0) {
    lines.push("## Top Solutions (by confidence)");
    lines.push("");
    lines.push("| Topic | Confidence | Tags |");
    lines.push("|-------|-----------:|------|");
    const sorted = [...solutions].sort((a, b) => b.confidence - a.confidence);
    const shown = sorted.slice(0, 5);
    for (const s of shown) {
      const tagClause = s.tags.length > 0 ? s.tags.slice(0, 4).join(", ") : "—";
      lines.push(
        "| [" +
          s.topic +
          "](./solutions/" +
          s.topic +
          ".md) | " +
          s.confidence.toFixed(2) +
          " | " +
          tagClause +
          " |",
      );
    }
    if (sorted.length > shown.length) {
      lines.push("");
      lines.push(
        "_… and " +
          String(sorted.length - shown.length) +
          " more in `solutions/` — see folder for full list._",
      );
    }
    lines.push("");
  }

  // Instinct patterns by tag
  if (patterns.length > 0) {
    lines.push("## Instinct Patterns (by tag)");
    lines.push("");
    const byTag = groupPatternsByTag(patterns);
    const sortedTags = [...byTag.keys()].sort();
    const shownTags = sortedTags.slice(0, 6);
    lines.push("| Tag | Count | Top confidence |");
    lines.push("|-----|------:|---------------:|");
    for (const tag of shownTags) {
      const group = byTag.get(tag);
      if (!group) continue;
      const top = group.reduce((m, p) => (p.confidence > m ? p.confidence : m), 0);
      lines.push(`| ${tag} | ${String(group.length)} | ${top.toFixed(2)} |`);
    }
    if (sortedTags.length > shownTags.length) {
      lines.push("");
      lines.push(
        "_… and " +
          String(sortedTags.length - shownTags.length) +
          " more tags — see `instincts.md` for full list._",
      );
    }
    lines.push("");
  }

  // Pointers
  lines.push("## Deep reads");
  lines.push("");
  lines.push("- Full patterns: `.forge/knowledge/instincts.md`");
  lines.push("- Full solutions: `.forge/knowledge/solutions/*.md`");
  lines.push("- Failure modes: `.forge/knowledge/known-failures.md`");
  lines.push("- Evolved rules: `.forge/knowledge/evolved-rules.md`");
  lines.push("");

  return lines.join("\n");
}

/**
 * Build the catalog end-to-end from raw inputs. Thin convenience wrapper
 * around {@link renderCatalog} that keeps the driver layer a one-liner.
 *
 * @internal
 */
export function buildCatalog(input: CatalogInput): string {
  return renderCatalog(input);
}

// ---------------------------------------------------------------------------
// Helpers (internal)
// ---------------------------------------------------------------------------

function groupPatternsByTag(patterns: Pattern[]): Map<string, Pattern[]> {
  const map = new Map<string, Pattern[]>();
  for (const p of patterns) {
    const tags = p.tags.length > 0 ? p.tags : ["(untagged)"];
    for (const tag of tags) {
      const existing = map.get(tag);
      if (existing) existing.push(p);
      else map.set(tag, [p]);
    }
  }
  return map;
}

function extractFrontmatter(content: string): string {
  const m = content.match(/^---\n([\s\S]*?)\n---\n/);
  return m ? m[1] : "";
}

function readYamlString(block: string, key: string): string | null {
  const re = new RegExp(`^${key}:\\s*(.+)$`, "m");
  const m = block.match(re);
  if (!m) return null;
  return m[1].trim().replace(/^"|"$/g, "");
}

function readYamlArray(block: string, key: string): string[] {
  const re = new RegExp(`^${key}:\\s*\\[(.*?)\\]\\s*$`, "m");
  const m = block.match(re);
  if (!m) return [];
  return m[1]
    .split(",")
    .map((s) => s.trim().replace(/^"|"$/g, ""))
    .filter((s) => s.length > 0);
}

function toIsoDate(d: Date): string {
  const year = d.getUTCFullYear().toString().padStart(4, "0");
  const month = (d.getUTCMonth() + 1).toString().padStart(2, "0");
  const day = d.getUTCDate().toString().padStart(2, "0");
  return `${year}-${month}-${day}`;
}
